### ISSUE TITLE
[BUG?] issue with Assets 'ic_launcher'

### ISSUE THREAD

**Issue by lewislepton** [guzzard/armory_sunvox#3]
just having a wee lok at this, since i love sunvox & love that something has been made for kha/armory.
but on trying in kha, it comes up with an error right away. may be a bug. but just wanted to share

```/usr/local/lib/kha/Sources/kha/Assets.hx:9: characters 1-7 : Duplicate class field declaration : ic_launcher```

not sure how this can be fixed, but thought to let you know. thanks

**Comment by guzzard** [comment]
Hi @lewislepton, not sure what's going on there. Looks like the error is in the source files for Kha? Both the armory example and the  kha example builds and runs fine on my computer. @luboslenco do you have any clue as to what the issue might be?

**Comment by luboslenco** [comment]
Hm I tested on macOS + git Kha and also seems to run here. Here is my `Assets/`folder:

<img width="282" alt="assets" src="https://user-images.githubusercontent.com/3685704/30935928-85d66db8-a3d2-11e7-90c2-4294dd549251.png">

With those files the project should build using `node Kha/make --run`. What command do you compile with? Is this on macOS? ic_launcher seems to be somehow related to Android, but not sure what is going on.

**Comment by lewislepton** [comment]
weird. got it working.
cheers folks.

but one thing that does pop up right when just doing a simple copy of the code is this. as it errors on the loading of the library. so wont work if running.

this is kha, not armory

<img width="543" alt="screen shot 2017-09-28 at 14 53 51" src="https://user-images.githubusercontent.com/11299322/30970420-fa7e61cc-a45c-11e7-80d7-d315139764b2.png">
<img width="594" alt="screen shot 2017-09-28 at 14 53 57" src="https://user-images.githubusercontent.com/11299322/30970423-fcda62e0-a45c-11e7-8b9e-08f81016f931.png">

**Comment by lewislepton** [comment]
it is on macOS with kode studio. ill just try on terminal. but should actually just come out the same

**Comment by luboslenco** [comment]
JS targets will sadly not work, as there is not a complete sunvox library available for that target yet. But hopefully soon.

Kore + Windows/Linux/macOS should work using `node Kha/make --run`.

**Comment by lewislepton** [comment]
AH HA. cool .cheers man. good to know. really would love to do a tutorial on this. though possibly wait until JS comes into play. because we can then have fun without waiting for the build in terminal

cheers again
